version: "3"

services:
  db:
    image: mariadb:10
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_USER: "$MYSQL_USER"
      MYSQL_PASSWORD: "$MYSQL_PASSWORD"
      MYSQL_DATABASE: "$MYSQL_DATABASE"
    volumes:
      - "./db:/var/lib/mysql"
  nginx:
    image: trafex/php-nginx
    depends_on: 
      - db
    ports:
      - "8080:8080"
    read_only: true
    volumes:
      - "./src:/var/www/html"
      - "./config/nginx.conf:/etc/nginx/nginx.conf"
      - "./config/fpm-pool.conf:/etc/php8/php-fpm.d/www.conf"
      - "./config/php.ini:/etc/php8/conf.d/custom.ini"
      - "./config/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf"
    tempfs:
      - "/tmp:size=10M"
    environment:
      DB_HOST: "db"
      DB_USER: "$MYSQL_USER"
      DB_PASSWORD: "$MYSQL_PASSWORD"
      DB_DATABASE: "$MYSQL_DATABASE"
